### ISSUE TITLE
Define scope of this Electron App's MVP

### ISSUE THREAD

**Issue by kanitw** [vega/voyager-electron#2]
> What do we want the electron app to be? What level of polish/features should it include? Is it intended to be a sample 'guide' to embedding voyager.

Let's discuss what's important as a MVP to demonstrate how to embed Voyager. 
I think it's still important what are the basic operations that Voyager wrapper would expect to do. 

# Input

## Important 

- Open an TSV.
- Open a JSON file.

## Less important

- ~~Open a `.vl.json` file and load both the data and encoding into the shelf~~ see #4

# Output

?

cc: @tafsiri  I'm replacing the note in the board with this issue :)

**Comment by tafsiri** [comment]
# Todo list.

## High Priority 

- [x] Open a JSON file.
- [x] Open an TSV.
- [x] Clean up initial view (fill window etc)
- [x] Make common keyboard shortcuts work (e.g. for quitting the app)
-  ~~Add documentation about how voyager is integrated~~ (this belongs in the voyager repo).

## Low Priority

- ~~Support drag and drop loading of above file types~~ See #6

**Comment by tafsiri** [comment]
@kanitw @vlandham. I've made a TODO list above for some generic things to do in the app. Open questions still include what if any output comes from voyager, but unless we have an idea of what we'd want to demonstrate in this app; that may be an issue better made in the main voyager repo.

**Comment by tafsiri** [comment]
Closing this as all the items are complete or broken out into other issues.
